import { Platform, StyleSheet } from "react-native";

const COLORS = {
  bg: "#F1F5F9",
  surface: "#FFFFFF",
  surfaceAlt: "#F8FAFC",
  text: "#1E293B",
  textMuted: "#64748B",
  primary: "#3B82F6",
  primaryDark: "#2563EB",
  success: "#22C55E",
  warning: "#F59E0B",
  danger: "#EF4444",
  purple: "#8B5CF6",
  border: "#E2E8F0",
  blueMuted: "#60A5FA",
  greenMuted: "#4ADE80",
  error: "#DC2626",
};

const shadow = (elevation = 2) =>
  Platform.select({
    ios: {
      shadowColor: "#0F172A",
      shadowOffset: {
        width: 0,
        height: Math.max(1, Math.round(elevation / 2)),
      },
      shadowOpacity: 0.06,
      shadowRadius: Math.max(4, elevation * 2),
    },
    android: { elevation },
    default: {},
  });

const styles = StyleSheet.create({
  appContainer: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  container: {
    flex: 1,
    paddingTop: 40,
    backgroundColor: COLORS.bg,
  },
  scrollView: {
    paddingHorizontal: 16,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "transparent",
    borderBottomWidth: 0,
    borderBottomColor: COLORS.border,
  },
  headerTitleApp: {
    fontSize: 26,
    fontWeight: "800",
    color: COLORS.text,
    letterSpacing: 0.2,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: COLORS.text,
    marginBottom: 18,
    paddingHorizontal: 16,
  },
  logoutButton: {
    padding: 5,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  backButtonText: {
    marginLeft: 5,
    fontSize: 18,
    color: COLORS.primary,
    fontWeight: "700",
  },
  menuContainer: {
    paddingTop: 6,
  },
  menuGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
  },
  menuButton: {
    width: "47%",
    aspectRatio: 1,
    backgroundColor: COLORS.surface,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 15,
    ...shadow(4),
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  menuLabel: {
    marginTop: 10,
    fontSize: 14,
    fontWeight: "700",
    color: COLORS.text,
    textAlign: "center",
    paddingHorizontal: 10,
  },
  formContainer: {
    padding: 20,
    backgroundColor: COLORS.surface,
    borderRadius: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadow(3),
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: COLORS.text,
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    paddingBottom: 10,
  },
  label: {
    fontSize: 14,
    color: COLORS.text,
    fontWeight: "700",
    marginBottom: 5,
  },
  localidadeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 15,
  },
  localidadePill: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: COLORS.primary,
    backgroundColor: COLORS.surface,
  },
  cidadePill: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: COLORS.primary,
    backgroundColor: COLORS.surface,
  },
  localidadePillSelected: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  localidadePillText: {
    color: COLORS.primary,
    fontWeight: "800",
  },
  localidadePillTextSelected: {
    color: COLORS.surface,
  },
  medicoSelectionBlock: {
    marginBottom: 15,
    padding: 14,
    backgroundColor: COLORS.surfaceAlt,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  input: {
    height: 50,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 14,
    marginBottom: 10,
    backgroundColor: COLORS.surface,
    color: COLORS.text,
  },
  flatListContainer: {
    maxHeight: 200,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: COLORS.surface,
  },
  flatListContent: {
    padding: 5,
  },
  pickerItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    backgroundColor: COLORS.surface,
  },
  pickerItemSelected: {
    backgroundColor: "#EFF6FF",
    borderLeftWidth: 5,
    borderLeftColor: COLORS.primary,
  },
  pickerItemSelectedText: {
    color: COLORS.primaryDark,
  },
  pickerItemText: {
    fontSize: 16,
    fontWeight: "800",
    color: COLORS.text,
  },
  pickerItemSubText: {
    fontSize: 12,
    color: COLORS.textMuted,
  },
  availabilityContainer: {
    marginBottom: 20,
    padding: 14,
    backgroundColor: COLORS.surfaceAlt,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  datePickerRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 15,
  },
  datePill: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.blueMuted,
    backgroundColor: COLORS.surface,
  },
  datePillSelected: {
    backgroundColor: COLORS.blueMuted,
  },
  datePillText: {
    color: COLORS.blueMuted,
    fontWeight: "600",
    fontSize: 13,
  },
  datePillTextSelected: {
    color: COLORS.surface,
  },
  timePickerRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 15,
  },
  timePill: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.greenMuted,
    backgroundColor: COLORS.surface,
  },
  timePillSelected: {
    backgroundColor: COLORS.greenMuted,
  },
  timePillText: {
    color: COLORS.greenMuted,
    fontWeight: "600",
    fontSize: 14,
  },
  timePillTextSelected: {
    color: COLORS.surface,
  },
  switchRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  buttonRow: {
    marginTop: 20,
  },
  button: {
    padding: 16,
    borderRadius: 16,
    minHeight: 54,
    alignItems: "center",
    marginBottom: 10,
    ...shadow(3),
  },
  saveButton: {
    backgroundColor: COLORS.success,
  },
  updateButton: {
    backgroundColor: COLORS.warning,
  },
  cancelButton: {
    backgroundColor: "#F97316",
  },
  disabledButton: {
    backgroundColor: "#CBD5E1",
  },
  buttonText: {
    color: COLORS.surface,
    fontSize: 16,
    fontWeight: "900",
  },
  listContainer: {
    padding: 16,
    marginBottom: 20,
  },
  emptyText: {
    textAlign: "center",
    color: COLORS.textMuted,
    fontStyle: "italic",
    marginTop: 12,
    fontSize: 15,
  },
  eventCard: {
    backgroundColor: COLORS.surface,
    padding: 18,
    borderRadius: 18,
    marginBottom: 12,
    borderLeftWidth: 5,
    borderLeftColor: COLORS.primary,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadow(2),
  },
  eventHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 10,
  },
  eventActions: {
    flexDirection: "column",
    gap: 5,
  },
  eventDate: {
    fontSize: 14,
    color: COLORS.text,
    fontWeight: "900",
    marginBottom: 5,
  },
  eventLocation: {
    fontSize: 12,
    color: COLORS.textMuted,
  },
  eventName: {
    fontSize: 16,
    fontWeight: "800",
    color: COLORS.text,
    marginBottom: 5,
  },
  eventObservation: {
    fontSize: 12,
    color: COLORS.textMuted,
  },
  editButton: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: COLORS.warning,
  },
  deleteButton: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: COLORS.danger,
  },
  actionButtonText: {
    color: COLORS.surface,
    fontSize: 10,
    fontWeight: "bold",
  },
  callContainer: {
    flex: 1,
    backgroundColor: "#334155",
  },
  videoContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  remoteVideo: {
    flex: 1,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  remoteVideoOff: {
    backgroundColor: "#1E293B",
  },
  localVideo: {
    position: "absolute",
    top: 50,
    right: 20,
    width: 100,
    height: 150,
    backgroundColor: "rgba(255,255,255,0.15)",
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  localVideoText: {
    color: "#fff",
    fontSize: 11,
  },
  infoContainer: {
    alignItems: "center",
    padding: 20,
  },
  doctorCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "#64748B",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 15,
  },
  statusText: {
    fontSize: 24,
    fontWeight: "bold",
    color: COLORS.greenMuted,
    marginBottom: 5,
  },
  statusTextConnecting: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FBBF24",
    marginBottom: 5,
  },
  nameText: {
    fontSize: 18,
    color: "#fff",
    fontWeight: "600",
  },
  specialtyText: {
    fontSize: 16,
    color: "#94A3B8",
  },
  controlButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
    padding: 20,
    backgroundColor: "transparent",
    position: "absolute",
    bottom: 0,
  },
  callButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  callButtonText: {
    color: "#FFFFFF",
    fontSize: 12,
    marginTop: 5,
    fontWeight: "bold",
  },
  smallControlButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 10,
  },
  dependentCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: COLORS.surface,
    padding: 18,
    borderRadius: 18,
    marginBottom: 12,
    borderLeftWidth: 5,
    borderLeftColor: COLORS.success,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadow(2),
  },
  dependentName: {
    fontSize: 18,
    fontWeight: "900",
    color: COLORS.text,
  },
  dependentDetails: {
    fontSize: 14,
    color: COLORS.textMuted,
  },
  addButton: {
    flexDirection: "row",
    backgroundColor: COLORS.primary,
    padding: 16,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    margin: 12,
    ...shadow(3),
  },
  addButtonText: {
    color: COLORS.surface,
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 10,
  },
  documentCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.surface,
    padding: 18,
    borderRadius: 18,
    marginBottom: 12,
    borderLeftWidth: 5,
    borderLeftColor: COLORS.purple,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadow(2),
  },
  docInfo: {
    marginLeft: 15,
    flex: 1,
  },
  documentName: {
    fontSize: 16,
    fontWeight: "900",
    color: COLORS.text,
  },
  documentDetails: {
    fontSize: 12,
    color: COLORS.textMuted,
  },
  downloadButton: {
    backgroundColor: COLORS.primary,
    padding: 12,
    borderRadius: 10,
  },
  listContent: {
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 30,
  },
  errorTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: COLORS.error,
    marginVertical: 15,
  },
  errorMessage: {
    fontSize: 16,
    color: COLORS.text,
    textAlign: "center",
    marginBottom: 20,
  },
  errorButton: {
    backgroundColor: COLORS.primary,
    padding: 16,
    borderRadius: 12,
    marginTop: 10,
  },
  infoCard: {
    backgroundColor: COLORS.surface,
    padding: 18,
    borderRadius: 18,
    marginBottom: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderLeftWidth: 5,
    borderLeftColor: COLORS.primary,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadow(2),
  },
  infoLabel: {
    fontSize: 16,
    fontWeight: "800",
    color: COLORS.text,
  },
  infoValue: {
    fontSize: 16,
    color: COLORS.textMuted,
    fontWeight: "normal",
  },
  typingIndicator: {
    paddingHorizontal: 15,
    marginBottom: 5,
    alignSelf: "flex-start",
  },
  typingText: {
    color: COLORS.textMuted,
    fontStyle: "italic",
  },
  sendButton: {
    backgroundColor: COLORS.primary,
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 10,
    ...shadow(2),
  },
  chatInput: {
    flex: 1,
    height: 48,
    backgroundColor: COLORS.surface,
    borderRadius: 24,
    paddingHorizontal: 16,
    fontSize: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    color: COLORS.text,
  },
  bloodTypeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    marginBottom: 20,
    gap: 8,
  },
  bloodTypePill: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: COLORS.blueMuted,
  },
  bloodTypePillSelected: {
    backgroundColor: COLORS.blueMuted,
  },
  bloodTypePillText: {
    color: COLORS.blueMuted,
    fontWeight: "bold",
    fontSize: 16,
  },
  bloodTypePillTextSelected: {
    color: COLORS.surface,
  },
  messageBubble: {
    maxWidth: "80%",
    padding: 14,
    borderRadius: 18,
    marginBottom: 10,
  },
  userBubble: {
    alignSelf: "flex-end",
    backgroundColor: COLORS.primary,
    borderBottomRightRadius: 4,
  },
  aiBubble: {
    alignSelf: "flex-start",
    backgroundColor: COLORS.surface,
    borderBottomLeftRadius: 4,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  messageText: {
    fontSize: 16,
  },
  userText: {
    color: COLORS.surface,
  },
  aiText: {
    color: COLORS.text,
  },
  messageList: {
    padding: 15,
    paddingBottom: 20,
  },
  chatContainer: {
    flex: 1,
    backgroundColor: COLORS.surface,
  },
  inputContainerChat: {
    flexDirection: "row",
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    backgroundColor: COLORS.surfaceAlt,
    alignItems: "center",
  },
  authContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 30,
    backgroundColor: COLORS.bg,
  },
  authCard: {
    width: "100%",
    maxWidth: 520,
    backgroundColor: COLORS.surface,
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...shadow(6),
  },
  logo: {
    fontFamily: "Merriweather",
    fontSize: 32,
    fontWeight: "900",
    marginBottom: 40,
    color: COLORS.primaryDark,
    letterSpacing: 0.2,
  },
  authTitle: {
    fontSize: 32,
    fontWeight: "900",
    marginBottom: 14,
    color: COLORS.text,
  },
  authSubtitle: {
    fontSize: 14,
    color: COLORS.textMuted,
    marginBottom: 18,
    fontWeight: "600",
  },
  authInput: {
    width: "100%",
    height: 56,
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    paddingHorizontal: 16,
    fontSize: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
    color: COLORS.text,
  },
  authButton: {
    width: "100%",
    height: 56,
    backgroundColor: COLORS.primary,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    ...shadow(6),
  },
  authButtonText: {
    color: COLORS.surface,
    fontSize: 18,
    fontWeight: "bold",
  },
  authLink: {
    marginTop: 20,
    color: COLORS.primary,
    fontSize: 16,
    fontWeight: "700",
  },
});

export default styles;
